-- AIX Vault Seed Script for Supabase
-- Run this in Supabase SQL Editor after 001_init.sql and 002_admin_roles.sql

-- 1. Insert Categories
insert into public.categories (id, name, slug, description, parent_id) values
  ('development', 'Developer Tools', 'development', 'Libraries, APIs, frameworks, and developer tools', null),
  ('design', 'Design Tools', 'design', 'UI/UX, design systems, typography, icons, and visual craft', null),
  ('development-developer-tools', 'Developer Tools', 'development-developer-tools', 'Developer Tools', 'development'),
  ('development-react', 'React', 'development-react', 'React', 'development'),
  ('development-vue', 'Vue', 'development-vue', 'Vue', 'development'),
  ('development-css', 'CSS', 'development-css', 'CSS', 'development'),
  ('development-javascript', 'JavaScript', 'development-javascript', 'JavaScript', 'development'),
  ('development-components', 'Components', 'development-components', 'Components', 'development'),
  ('development-libraries', 'Libraries', 'development-libraries', 'Libraries', 'development'),
  ('development-apis', 'APIs', 'development-apis', 'APIs', 'development'),
  ('development-open-source', 'Open Source', 'development-open-source', 'Open Source', 'development'),
  ('development-ai-tools', 'AI Tools', 'development-ai-tools', 'AI Tools', 'development'),
  ('development-documentation', 'Documentation', 'development-documentation', 'Documentation', 'development'),
  ('design-ui-ux', 'UI/UX', 'design-ui-ux', 'UI/UX', 'design'),
  ('design-design-systems', 'Design Systems', 'design-design-systems', 'Design Systems', 'design'),
  ('design-typography', 'Typography', 'design-typography', 'Typography', 'design'),
  ('design-icons', 'Icons', 'design-icons', 'Icons', 'design'),
  ('design-colors', 'Colors', 'design-colors', 'Colors', 'design'),
  ('design-illustration', 'Illustration', 'design-illustration', 'Illustration', 'design'),
  ('design-3d', '3D', 'design-3d', '3D', 'design'),
  ('design-motion', 'Motion', 'design-motion', 'Motion', 'design'),
  ('design-branding', 'Branding', 'design-branding', 'Branding', 'design'),
  ('design-ai-design', 'AI Design', 'design-ai-design', 'AI Design', 'design'),
  ('design-inspiration', 'Inspiration', 'design-inspiration', 'Inspiration', 'design'),
  ('design-assets', 'Assets', 'design-assets', 'Assets', 'design')
on conflict (id) do nothing;

-- 2. Insert Tags
insert into public.tags (id, name, slug) values
  ('minimal', 'minimal', 'minimal'),
  ('free', 'free', 'free'),
  ('open-source', 'open-source', 'open-source'),
  ('figma', 'figma', 'figma'),
  ('react', 'react', 'react'),
  ('saas', 'saas', 'saas'),
  ('mobile', 'mobile', 'mobile'),
  ('web', 'web', 'web'),
  ('productivity', 'productivity', 'productivity'),
  ('typography', 'typography', 'typography'),
  ('icons', 'icons', 'icons'),
  ('animation', 'animation', 'animation'),
  ('3d', '3d', '3d'),
  ('ai', 'ai', 'ai'),
  ('design-system', 'design-system', 'design-system'),
  ('components', 'components', 'components'),
  ('css', 'css', 'css'),
  ('collaboration', 'collaboration', 'collaboration'),
  ('prototype', 'prototype', 'prototype'),
  ('photos', 'photos', 'photos'),
  ('color', 'color', 'color'),
  ('research', 'research', 'research'),
  ('illustration', 'illustration', 'illustration')
on conflict (id) do nothing;

-- 3. Insert Collections
insert into public.collections (id, name, slug, description) values
  ('ui-tools', 'UI Tools', 'ui-tools', 'Interface design, component libraries, and visual craft'),
  ('ai-tools', 'AI Tools', 'ai-tools', 'Artificial intelligence, generative models, and copilots'),
  ('dev-tools', 'Dev Tools', 'dev-tools', 'Development platforms, libraries, and tools'),
  ('design-tools', 'Design Tools', 'design-tools', 'Interface design, icons, and visual craft'),
  ('typography', 'Typography', 'typography', 'Typography libraries, foundries, and type specimens'),
  ('productivity', 'Productivity', 'productivity', 'Workspace apps, task management, and workflow tools')
on conflict (id) do nothing;

-- 4. Insert Resources
insert into public.resources (id, name, slug, description, url, domain, type, category_id, is_public) values
  ('figma', 'Figma', 'figma', 'Design and collaboration platform', 'https://www.figma.com', 'figma.com', 'tool', 'design-ui-ux', true),
  ('framer', 'Framer', 'framer', 'Design and publish production websites', 'https://www.framer.com', 'framer.com', 'tool', 'design-ui-ux', true),
  ('linear', 'Linear', 'linear', 'Product development and issue tracking', 'https://linear.app', 'linear.app', 'tool', 'development-developer-tools', true),
  ('notion', 'Notion', 'notion', 'Connected workspace for notes and docs', 'https://www.notion.so', 'notion.so', 'tool', 'development-developer-tools', true),
  ('vercel', 'Vercel', 'vercel', 'Platform for frontend teams and Next.js', 'https://vercel.com', 'vercel.com', 'tool', 'development-developer-tools', true),
  ('github', 'GitHub', 'github', 'Code hosting and collaboration', 'https://github.com', 'github.com', 'tool', 'development-open-source', true),
  ('supabase', 'Supabase', 'supabase', 'Open source Postgres platform', 'https://supabase.com', 'supabase.com', 'tool', 'development-apis', true),
  ('shadcn-ui', 'shadcn/ui', 'shadcnui', 'Accessible component primitives for React', 'https://ui.shadcn.com', 'ui.shadcn.com', 'component-library', 'development-components', true),
  ('radix-ui', 'Radix UI', 'radix-ui', 'Unstyled accessible component primitives', 'https://www.radix-ui.com', 'radix-ui.com', 'component-library', 'development-components', true),
  ('lucide', 'Lucide', 'lucide', 'Open source icon library', 'https://lucide.dev', 'lucide.dev', 'icon-library', 'design-icons', true),
  ('react', 'React', 'react', 'Library for web and native user interfaces', 'https://react.dev', 'react.dev', 'library', 'development-react', true),
  ('react-aria', 'React Aria', 'react-aria', 'Accessible UI primitives for React', 'https://react-spectrum.adobe.com/react-aria/', 'react-spectrum.adobe.com', 'library', 'development-react', true),
  ('tailwind', 'Tailwind CSS', 'tailwind-css', 'Utility-first CSS framework', 'https://tailwindcss.com', 'tailwindcss.com', 'library', 'development-css', true),
  ('webflow', 'Webflow', 'webflow', 'Visual website design and CMS', 'https://webflow.com', 'webflow.com', 'tool', 'design-ui-ux', true),
  ('mobbin', 'Mobbin', 'mobbin', 'Mobile and web design references', 'https://mobbin.com', 'mobbin.com', 'website', 'design-inspiration', true),
  ('awwwards', 'Awwwards', 'awwwards', 'Awards for creative web design', 'https://www.awwwards.com', 'awwwards.com', 'community', 'design-inspiration', true),
  ('arena', 'Are.na', 'arena', 'Visual research and collections', 'https://www.are.na', 'are.na', 'community', 'design-inspiration', true),
  ('raindrop', 'Raindrop', 'raindrop', 'Bookmark manager for saving the web', 'https://raindrop.io', 'raindrop.io', 'tool', 'development-developer-tools', true),
  ('savee', 'Savee', 'savee', 'Visual inspiration bookmarking', 'https://savee.it', 'savee.it', 'tool', 'design-inspiration', true),
  ('google-fonts', 'Google Fonts', 'google-fonts', 'Free font library for the web', 'https://fonts.google.com', 'fonts.google.com', 'font', 'design-typography', true),
  ('fontshare', 'Fontshare', 'fontshare', 'Quality fonts with free licenses', 'https://www.fontshare.com', 'fontshare.com', 'font', 'design-typography', true),
  ('unsplash', 'Unsplash', 'unsplash', 'Free high-resolution photography', 'https://unsplash.com', 'unsplash.com', 'website', 'design-assets', true),
  ('coolors', 'Coolors', 'coolors', 'Color palette generator', 'https://coolors.co', 'coolors.co', 'color', 'design-colors', true),
  ('nextjs', 'Next.js', 'nextjs', 'React framework for production', 'https://nextjs.org', 'nextjs.org', 'library', 'development-react', true),
  ('cursor', 'Cursor', 'cursor', 'AI code editor', 'https://cursor.com', 'cursor.com', 'ai-tool', 'development-ai-tools', true),
  ('claude', 'Claude', 'claude', 'AI assistant for writing and code', 'https://claude.ai', 'claude.ai', 'ai-tool', 'development-ai-tools', true),
  ('chatgpt', 'ChatGPT', 'chatgpt', 'Conversational AI from OpenAI', 'https://chatgpt.com', 'chatgpt.com', 'ai-tool', 'development-ai-tools', true),
  ('v0', 'v0', 'v0', 'Generative UI from Vercel', 'https://v0.dev', 'v0.dev', 'ai-tool', 'design-ai-design', true),
  ('midjourney', 'Midjourney', 'midjourney', 'Image generation for design exploration', 'https://www.midjourney.com', 'midjourney.com', 'ai-tool', 'design-ai-design', true),
  ('heroicons', 'Heroicons', 'heroicons', 'Icons by the makers of Tailwind', 'https://heroicons.com', 'heroicons.com', 'icon-library', 'design-icons', true),
  ('phosphor', 'Phosphor Icons', 'phosphor-icons', 'Flexible icon family for interfaces', 'https://phosphoricons.com', 'phosphoricons.com', 'icon-library', 'design-icons', true),
  ('storybook', 'Storybook', 'storybook', 'Frontend workshop for UI components', 'https://storybook.js.org', 'storybook.js.org', 'tool', 'development-components', true),
  ('relume', 'Relume', 'relume', 'Sitemaps, wireframes, and Webflow libraries', 'https://www.relume.io', 'relume.io', 'ui-kit', 'design-ui-ux', true),
  ('untitled-ui', 'Untitled UI', 'untitled-ui', 'Figma UI kit and design system', 'https://www.untitledui.com', 'untitledui.com', 'ui-kit', 'design-design-systems', true),
  ('inter', 'Inter', 'inter', 'Typeface designed for computer screens', 'https://rsms.me/inter/', 'rsms.me', 'font', 'design-typography', true),
  ('geist', 'Geist', 'geist', 'Typeface by Vercel', 'https://vercel.com/font', 'vercel.com', 'font', 'design-typography', true),
  ('raycast', 'Raycast', 'raycast', 'Launcher and productivity tool', 'https://www.raycast.com', 'raycast.com', 'tool', 'development-developer-tools', true),
  ('astro', 'Astro', 'astro', 'Web framework for content-driven sites', 'https://astro.build', 'astro.build', 'library', 'development-javascript', true),
  ('mdn', 'MDN Web Docs', 'mdn-web-docs', 'Web platform documentation', 'https://developer.mozilla.org', 'developer.mozilla.org', 'article', 'development-documentation', true),
  ('css-tricks', 'CSS-Tricks', 'css-tricks', 'Guides and articles for CSS and front-end', 'https://css-tricks.com', 'css-tricks.com', 'article', 'development-documentation', true)
on conflict (id) do nothing;

-- 5. Insert Resource Tags
insert into public.resource_tags (resource_id, tag_id) values
  ('figma', 'figma'),
  ('figma', 'collaboration'),
  ('figma', 'prototype'),
  ('figma', 'web'),
  ('framer', 'web'),
  ('framer', 'animation'),
  ('framer', 'prototype'),
  ('linear', 'saas'),
  ('linear', 'productivity'),
  ('linear', 'web'),
  ('notion', 'productivity'),
  ('notion', 'collaboration'),
  ('notion', 'saas'),
  ('vercel', 'web'),
  ('vercel', 'saas'),
  ('github', 'open-source'),
  ('github', 'collaboration'),
  ('github', 'web'),
  ('supabase', 'open-source'),
  ('supabase', 'web'),
  ('shadcn-ui', 'react'),
  ('shadcn-ui', 'components'),
  ('shadcn-ui', 'open-source'),
  ('shadcn-ui', 'design-system'),
  ('radix-ui', 'react'),
  ('radix-ui', 'components'),
  ('radix-ui', 'open-source'),
  ('lucide', 'icons'),
  ('lucide', 'open-source'),
  ('lucide', 'free'),
  ('react', 'react'),
  ('react', 'open-source'),
  ('react', 'web'),
  ('react-aria', 'react'),
  ('react-aria', 'components'),
  ('react-aria', 'open-source'),
  ('tailwind', 'css'),
  ('tailwind', 'open-source'),
  ('tailwind', 'web'),
  ('webflow', 'web'),
  ('webflow', 'saas'),
  ('mobbin', 'mobile'),
  ('mobbin', 'web'),
  ('awwwards', 'web'),
  ('arena', 'minimal'),
  ('arena', 'research'),
  ('raindrop', 'productivity'),
  ('raindrop', 'web'),
  ('savee', 'web'),
  ('google-fonts', 'typography'),
  ('google-fonts', 'free'),
  ('google-fonts', 'web'),
  ('fontshare', 'typography'),
  ('fontshare', 'free'),
  ('unsplash', 'photos'),
  ('unsplash', 'free'),
  ('coolors', 'color'),
  ('coolors', 'web'),
  ('coolors', 'free'),
  ('nextjs', 'react'),
  ('nextjs', 'web'),
  ('nextjs', 'open-source'),
  ('cursor', 'ai'),
  ('cursor', 'productivity'),
  ('claude', 'ai'),
  ('claude', 'productivity'),
  ('chatgpt', 'ai'),
  ('chatgpt', 'productivity'),
  ('v0', 'ai'),
  ('v0', 'react'),
  ('v0', 'components'),
  ('midjourney', 'ai'),
  ('midjourney', 'illustration'),
  ('heroicons', 'icons'),
  ('heroicons', 'open-source'),
  ('heroicons', 'free'),
  ('phosphor', 'icons'),
  ('phosphor', 'open-source'),
  ('phosphor', 'free'),
  ('storybook', 'components'),
  ('storybook', 'open-source'),
  ('relume', 'web'),
  ('relume', 'figma'),
  ('relume', 'components'),
  ('untitled-ui', 'figma'),
  ('untitled-ui', 'design-system'),
  ('inter', 'typography'),
  ('inter', 'free'),
  ('inter', 'open-source'),
  ('geist', 'typography'),
  ('geist', 'web'),
  ('raycast', 'productivity'),
  ('astro', 'web'),
  ('astro', 'open-source'),
  ('mdn', 'web'),
  ('mdn', 'free'),
  ('css-tricks', 'css'),
  ('css-tricks', 'web')
on conflict do nothing;

-- 6. Insert Collection Resources
insert into public.collection_resources (collection_id, resource_id) values
  ('ui-tools', 'figma'),
  ('ui-tools', 'framer'),
  ('ui-tools', 'shadcn-ui'),
  ('ui-tools', 'radix-ui'),
  ('ui-tools', 'lucide'),
  ('ui-tools', 'relume'),
  ('ui-tools', 'untitled-ui'),
  ('ai-tools', 'cursor'),
  ('ai-tools', 'claude'),
  ('ai-tools', 'chatgpt'),
  ('ai-tools', 'v0'),
  ('ai-tools', 'midjourney'),
  ('dev-tools', 'github'),
  ('dev-tools', 'vercel'),
  ('dev-tools', 'supabase'),
  ('dev-tools', 'linear'),
  ('dev-tools', 'react'),
  ('dev-tools', 'tailwind'),
  ('dev-tools', 'nextjs'),
  ('dev-tools', 'astro'),
  ('dev-tools', 'storybook'),
  ('dev-tools', 'css-tricks'),
  ('design-tools', 'mobbin'),
  ('design-tools', 'awwwards'),
  ('design-tools', 'arena'),
  ('design-tools', 'savee'),
  ('design-tools', 'coolors'),
  ('design-tools', 'unsplash'),
  ('typography', 'google-fonts'),
  ('typography', 'fontshare'),
  ('typography', 'inter'),
  ('typography', 'geist'),
  ('productivity', 'notion'),
  ('productivity', 'raycast'),
  ('productivity', 'linear'),
  ('productivity', 'raindrop')
on conflict do nothing;
